/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JFrame;
import Utilidades.Fondo;

/**
 *
 * @author Gaby Lainez
 */
public class VistaEspecialidad extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuario
     */
    public VistaEspecialidad() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         this.setLocationRelativeTo(this);
        this.Fondo.setBorder(new Fondo("/imagenes/espeFondo.jpg"));
        
    }
  public void iniciar() {
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEspecialidades = new RSMaterialComponent.RSTableMetroCustom();
        btnBuscar = new javax.swing.JButton();
        btnAgregarEspecialidad = new RSMaterialComponent.RSButtonMaterialIconTwo();
        buscarUsuario = new RSMaterialComponent.RSTextFieldMaterial();
        btnEliminarEspecialidad = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btnEditarEspecialidad = new RSMaterialComponent.RSButtonMaterialIconTwo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEspecialidades.setBackground(new java.awt.Color(204, 153, 255));
        tblEspecialidades.setForeground(new java.awt.Color(0, 0, 0));
        tblEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEspecialidades.setBackgoundHead(new java.awt.Color(153, 0, 255));
        tblEspecialidades.setBackgoundHover(new java.awt.Color(255, 102, 255));
        tblEspecialidades.setBorderHead(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblEspecialidades.setBorderRows(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        tblEspecialidades.setColorPrimary(new java.awt.Color(51, 102, 255));
        tblEspecialidades.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tblEspecialidades.setColorSecondary(new java.awt.Color(102, 153, 255));
        tblEspecialidades.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tblEspecialidades.setForegroundHover(new java.awt.Color(0, 0, 0));
        tblEspecialidades.setOpaque(false);
        jScrollPane2.setViewportView(tblEspecialidades);

        Fondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 792, 381));

        btnBuscar.setBackground(new java.awt.Color(0, 153, 153));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        Fondo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, 42));

        btnAgregarEspecialidad.setBackground(new java.awt.Color(51, 51, 255));
        btnAgregarEspecialidad.setForeground(new java.awt.Color(102, 0, 255));
        btnAgregarEspecialidad.setText("AGREGAR");
        btnAgregarEspecialidad.setBackgroundHover(new java.awt.Color(204, 0, 255));
        btnAgregarEspecialidad.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        Fondo.add(btnAgregarEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 443, 126, -1));

        buscarUsuario.setForeground(new java.awt.Color(153, 0, 204));
        buscarUsuario.setCaretColor(new java.awt.Color(204, 255, 255));
        buscarUsuario.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });
        Fondo.add(buscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 447, 258, -1));

        btnEliminarEspecialidad.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarEspecialidad.setForeground(new java.awt.Color(102, 0, 255));
        btnEliminarEspecialidad.setText("ELIMINAR");
        btnEliminarEspecialidad.setBackgroundHover(new java.awt.Color(204, 0, 255));
        btnEliminarEspecialidad.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_SWEEP);
        Fondo.add(btnEliminarEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 443, 122, -1));

        btnEditarEspecialidad.setBackground(new java.awt.Color(255, 255, 153));
        btnEditarEspecialidad.setForeground(new java.awt.Color(102, 0, 255));
        btnEditarEspecialidad.setText("EDITAR");
        btnEditarEspecialidad.setBackgroundHover(new java.awt.Color(204, 0, 255));
        btnEditarEspecialidad.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER_SHARED);
        Fondo.add(btnEditarEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 443, 119, -1));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 912, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarUsuarioActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaEspecialidad().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    public RSMaterialComponent.RSButtonMaterialIconTwo btnAgregarEspecialidad;
    public javax.swing.JButton btnBuscar;
    public RSMaterialComponent.RSButtonMaterialIconTwo btnEditarEspecialidad;
    public RSMaterialComponent.RSButtonMaterialIconTwo btnEliminarEspecialidad;
    public RSMaterialComponent.RSTextFieldMaterial buscarUsuario;
    private javax.swing.JScrollPane jScrollPane2;
    public RSMaterialComponent.RSTableMetroCustom tblEspecialidades;
    // End of variables declaration//GEN-END:variables
}
