/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import utilidades.Fondo;

/**
 *
 * @author Gaby Lainez
 */
public class VistaEspecialidad extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuario
     */
    public VistaEspecialidad() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.Fondo.setBorder(new Fondo("/imagenes/espeFondo.jpg"));
        
    }
  public void iniciar() {
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEspecialidades = new RSMaterialComponent.RSTableMetroCustom();
        btnAgregarEspecialidad = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btnEliminarEspecialidad = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btnEditarEspecialidad = new RSMaterialComponent.RSButtonMaterialIconTwo();
        buscarUsuario = new RSMaterialComponent.RSTextFieldMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEspecialidades.setBackground(new java.awt.Color(0, 0, 0));
        tblEspecialidades.setForeground(new java.awt.Color(153, 153, 153));
        tblEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEspecialidades.setBackgoundHead(new java.awt.Color(153, 0, 255));
        tblEspecialidades.setBackgoundHover(new java.awt.Color(255, 102, 255));
        tblEspecialidades.setBorderHead(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblEspecialidades.setBorderRows(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        tblEspecialidades.setColorPrimary(new java.awt.Color(51, 102, 255));
        tblEspecialidades.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tblEspecialidades.setColorSecondary(new java.awt.Color(102, 153, 255));
        tblEspecialidades.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tblEspecialidades.setForegroundHover(new java.awt.Color(0, 0, 0));
        tblEspecialidades.setOpaque(false);
        jScrollPane2.setViewportView(tblEspecialidades);

        btnAgregarEspecialidad.setBackground(new java.awt.Color(51, 51, 255));
        btnAgregarEspecialidad.setForeground(new java.awt.Color(102, 0, 255));
        btnAgregarEspecialidad.setText("AGREGAR");
        btnAgregarEspecialidad.setBackgroundHover(new java.awt.Color(204, 0, 255));
        btnAgregarEspecialidad.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);

        btnEliminarEspecialidad.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarEspecialidad.setForeground(new java.awt.Color(102, 0, 255));
        btnEliminarEspecialidad.setText("ELIMINAR");
        btnEliminarEspecialidad.setBackgroundHover(new java.awt.Color(204, 0, 255));
        btnEliminarEspecialidad.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE_SWEEP);

        btnEditarEspecialidad.setBackground(new java.awt.Color(255, 255, 153));
        btnEditarEspecialidad.setForeground(new java.awt.Color(102, 0, 255));
        btnEditarEspecialidad.setText("EDITAR");
        btnEditarEspecialidad.setBackgroundHover(new java.awt.Color(204, 0, 255));
        btnEditarEspecialidad.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FOLDER_SHARED);

        buscarUsuario.setForeground(new java.awt.Color(153, 0, 204));
        buscarUsuario.setCaretColor(new java.awt.Color(204, 255, 255));
        buscarUsuario.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditarEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEspecialidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    public RSMaterialComponent.RSButtonMaterialIconTwo btnAgregarEspecialidad;
    public RSMaterialComponent.RSButtonMaterialIconTwo btnEditarEspecialidad;
    public RSMaterialComponent.RSButtonMaterialIconTwo btnEliminarEspecialidad;
    public RSMaterialComponent.RSTextFieldMaterial buscarUsuario;
    private javax.swing.JScrollPane jScrollPane2;
    public RSMaterialComponent.RSTableMetroCustom tblEspecialidades;
    // End of variables declaration//GEN-END:variables
}
