/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Utilidades.Fondo;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;

/**
 *
 * @author Gaby Laínez
 */
public class VistaFomularioReceta extends javax.swing.JFrame {

    /**
     * Creates new form VistaFomularioReceta
     */
    public VistaFomularioReceta() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.Fondo.setBorder(new Fondo("/imagenes/frReceta.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spCantidad = new javax.swing.JSpinner();
        spDosis = new javax.swing.JSpinner();
        comboConsulta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtIDReceta = new javax.swing.JTextField();
        Btnguardar = new javax.swing.JButton();
        Fondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 222, 241));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("CANTIDAD MEDICAMENTO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("DOSIS DIARIA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("SINTOMAS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 30));

        spCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(spCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 80, 30));

        spDosis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spDosis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(spDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 80, 30));

        comboConsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE:" }));
        jPanel1.add(comboConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 290, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID RECETA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 30));

        txtIDReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDRecetaActionPerformed(evt);
            }
        });
        txtIDReceta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDRecetaKeyTyped(evt);
            }
        });
        jPanel1.add(txtIDReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 200, 40));

        Btnguardar.setBackground(new java.awt.Color(235, 100, 115));
        Btnguardar.setText("GUARDAR");
        jPanel1.add(Btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 99, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 400, 260));

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 260));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDRecetaActionPerformed

    private void txtIDRecetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDRecetaKeyTyped
       
         this.txtIDReceta.setText(this.txtIDReceta.getText().toUpperCase());
        char c = evt.getKeyChar();
        
        
        if (!Character.isDigit(c) && c != '-') {
            evt.consume();
            this.txtIDReceta.setBackground(Color.pink);
            this.txtIDReceta.setBorder(BorderFactory.createLineBorder(Color.red));
            this.lbError.setText("---> ERROR SOLO NUMEROS Y GUION <---");
            
        } else {
            this.txtIDReceta.setBackground(Color.white);
            this.txtIDReceta.setText(this.txtIDReceta.getText().toUpperCase());
            this.txtIDReceta.setBorder(BorderFactory.createLineBorder(new Color(0,120,215),1));
            this.lbError.setText(" ");
        }
        
    }//GEN-LAST:event_txtIDRecetaKeyTyped

    private void spCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spCantidadKeyTyped

        
    }//GEN-LAST:event_spCantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFomularioReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFomularioReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFomularioReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFomularioReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFomularioReceta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btnguardar;
    public javax.swing.JPanel Fondo;
    public javax.swing.JComboBox<String> comboConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lbError;
    public javax.swing.JSpinner spCantidad;
    public javax.swing.JSpinner spDosis;
    public javax.swing.JTextField txtIDReceta;
    // End of variables declaration//GEN-END:variables
}
